ecomerce/ecomerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import homePage, contact_page, about_page, login_page, register_page


urlpatterns = [
	url(r'^$', homePage, name='home'),
	url(r'^contact/$', contact_page, name='contact'),
	url(r'^about/$', about_page),
    url(r'^login/$', login_page, name='login'),
    url(r'^register/$', register_page, name='register'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^admin/', admin.site.urls),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomerce/products/urls.py
from django.conf.urls import url

from .views import (
    ProductListView,
    ProductDetailSlugView
    )


urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    ]

ecomerce/search/urls.py
from django.conf.urls import url

from .views import (
    searchproductview,
    )


urlpatterns = [
    url(r'^$', searchproductview, name='search'),
    ]

ecomerce/products/models.py
import random
import os
from django.db import models
from .utils import unique_slug_generator
from django.db.models.signals import pre_save, post_save

def get_filename_ext(filepath):
	base_name  = os.path.basename(filepath)
	name, ext  = os.path.splitext(base_name)
	return name, ext


def upload_img_path(instance, filename):
	print(instance)
	print(filename)
	new_filename = random.randint(1,3985684578)
	name, ext  = get_filename_ext(filename)
	final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
	return "products/{new_filename}/{final_filename}".format(new_filename=new_filename, final_filename=final_filename)



# Create your models here.
class Product(models.Model):
	title 		=	models.CharField(max_length=120)
	slug 		=	models.SlugField(blank=True, unique=True)
	description =	models.TextField()
	price 		=	models.DecimalField(decimal_places=2, max_digits=19, default=39.99)
	image 		=	models.ImageField(upload_to = upload_img_path, null=True, blank=True)
	featured 	=	models.BooleanField(default=False)
	active 		=	models.BooleanField(default=True)


	def get_absolute_url(self):
		return "/products/{slug}/".format(slug=self.slug)

	def __str__(self):
		return self.title


def product_pre_save_reciever(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_reciever, sender=Product)

ecomerce/search/models.py
from django.db import models

# Create your models here.

ecomerce/ecomerce/forms.py
from django import forms
from django.contrib.auth import get_user_model

User=get_user_model()


class ContactForm(forms.Form):
	fullName = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control","id":"form_full"}))
	Email 	 =	forms.EmailField()
	content  = forms.CharField()



class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(forms.Form):
	username = forms.CharField()
	Email 	 = forms.EmailField(widget=forms.EmailInput)
	password = forms.CharField(widget=forms.PasswordInput)
	password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)


	def clean_username(self):
		username = self.cleaned_data.get("username")
		qs = User.objects.filter(username=username)

		if qs.exists():
			raise forms.ValidationError("username exists")

		return username


	def clean_Email(self):
		username = self.cleaned_data.get("Email")
		qs = User.objects.filter(email=username)

		if qs.exists():
			raise forms.ValidationError("email exists")

		return username


	def clean(self):
		data = self.cleaned_data
		password = self.cleaned_data.get("password")
		password2 = self.cleaned_data.get("password2")

		if password != password2:
			raise forms.ValidationError("Password must match")

		return data

ecomerce/ecomerce/views.py
from django.contrib.auth import login, authenticate, get_user_model
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ContactForm, LoginForm, RegisterForm

def homePage(request):
	context = {
	"home":"welcome to home"
	}
	return render(request,'home_page.html', context)

def about_page(request):
	context = {
	"home":"About page"
	}
	return render(request,'home_page.html', context)

def contact_page(request):
	form = ContactForm()
	context = {
	"home":"contact page",
	"form":form
	}

	if request.method == "POST":
		print(request.POST.get('name'))
	return render(request,'ontact.html', context)


def login_page(request):
	form = LoginForm(request.POST or None)
	context = {
	"form":form
	}
	# print(request.user.is_authenticated())
	if form.is_valid():
		print(form.cleaned_data)
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user 	=	authenticate(request, username=username, password=password)
		# print(request.user.is_authenticated())

		if user is not None:
			# print(request.user.is_authenticated())
			login(request, user)
			return redirect("/login")
		else:
			print("Error")
		
	return render(request, "auth/login.html", context)

User = get_user_model()
def register_page(request):
	form = RegisterForm(request.POST or None)
	context = {
	"form":form
	}
	if form.is_valid():
		print(form.cleaned_data)
		username = form.cleaned_data.get("username")
		email = form.cleaned_data.get("Email")
		password = form.cleaned_data.get("password")
		new_user = User.objects.create_user(username, email, password)
		print(new_user)
	return render(request, "auth/register.html", context)

ecomerce/products/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import Product



class ProductListView(ListView):
	queryset 	=	Product.objects.all()
	template_name = 'products/list.html'


def product_list_view(request):
	queryset = Product.objects.all()

	context = {
	'object_list':queryset
	}
	return render(request,"products/list.html", context)
	


class ProductDetailView(DetailView):
	queryset 	=	Product.objects.all()
	template_name = 'products/detail.html'


class ProductDetailSlugView(DetailView):
	queryset 	=	Product.objects.all()
	template_name = 'products/detail.html'


def product_detail_view(request, pk):
	instance = get_object_or_404(Product, pk=pk)

	context = {
	'object':instance
	}
	return render(request,"products/detail.html", context)

ecomerce/search/views.py
from django.shortcuts import render
from products.models import Product
# Create your views here.
def searchproductview(request):
	query = request.GET.get('q')
	if query is not None:
		queryset = Product.objects.filter(title__icontains=query)
	else:
		queryset = Product.objects.none()
	context = {
	'object_list':queryset
	}
	return render(request,"products/list.html", context)

ecomerce/products/templates/products/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{{ object.title }}<br>
{{ object.description }}

<img src="{{ object.image.url }}" class="img-thumbnail" style="height:100px; width:200px">


{% endblock %}

ecomerce/products/templates/products/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
{% for obj in object_list %}
<div class="col col-lg-3  mt-5 m-3">
	{% include 'products/snippets/card.html' with instance=obj %}
</div>
{% endfor %}
</div>
{% endblock %}

ecomerce/products/templates/products/snippets/card.html
<div class="card border border-success" style="width: 18rem;">
	{% if instance.image %}
  <img class="card-img-top" src="{{ instance.image.url }}" alt="Card image cap" style="height:150px">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{instance.title}}</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">View</a>
  </div>
</div>

ecomerce/products/templates/snippets/card.html
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

ecomerce/templates/base.html
{% load static %}
{% url "home" as home_url %}
{% url "contact" as contact_url %}
{% url "products:list" as product_url %}
{% url "login" as login_url %}
{% url "register" as register_url %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="#">Ecommerce</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == product_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_url }}">Products</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <div class="container">
    {% block content %}

    {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

ecomerce/templates/home_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="card mb-3">
  <img class="card-img-top" src=".../100px180/" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
</div>
{% endblock %}

ecomerce/templates/ontact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="card mb-3">
  <img class="card-img-top" src=".../100px180/" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
</div>
{% endblock %}