DocumentVerification/DocumentVerification/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('',include('docker.urls', namespace='docker')),
    path('admin/', admin.site.urls),
]

DocumentVerification/docker/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from . import views

app_name = 'docker'

urlpatterns = [
	path('', views.home, name='home'),
	path('signup/', views.SignUpView, name='signup'),
	path('docview/<int:userid>/', views.PersonDocumentView, name='docview'),
	path('docverify/<int:userid>/', views.DocVerify, name='docverify'),
	path('newdoc/', views.DocCreateView, name='newdoc'),
	path('userlist/', views.UserListView, name='userlist'),
	path('doclist/', views.DocumentListView, name='doclist'),
	path('docval/<int:docid>/', views.DeleteDoc, name='docdelete'),
	path('login/', LoginView.as_view(template_name='login.html'), name='login'),
	
	path('logout/', views.LogotView, name='logout'),
	
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DocumentVerification/docker/models.py
from django.db import models
import os
from django.contrib.auth.models import User
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.core.exceptions import ValidationError

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return '{0}/{1}'.format(instance.user.username, filename)


def validate_file_extension(value):
	ext = os.path.splitext(value.name)[1]  
	valid_extensions = ['.pdf']
	if not ext.lower() in valid_extensions:
		raise ValidationError(u'Please Upload PDF file only')

class Documents(models.Model):
	user 				=	models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	Birth_Certificate 	=   models.FileField(upload_to=user_directory_path, validators=[validate_file_extension])
	Degree_Certificate 	=   models.FileField(upload_to=user_directory_path, validators=[validate_file_extension])
	Verification 		=	models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

@receiver(models.signals.post_delete, sender=Documents)
def auto_delete_file_on_delete(sender, instance, **kwargs):
	if (instance.Birth_Certificate or Degree_Certificate):
		if os.path.isfile(instance.Birth_Certificate.path or instance.Degree_Certificate.path):
			os.remove(instance.Birth_Certificate.path)
			os.remove(instance.Degree_Certificate.path)


	
# Create your models here.

DocumentVerification/docker/forms.py
from django import forms
from .models import Documents
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
	last_name  = forms.CharField(max_length=30, required=False, help_text='Optional')
	email 	   = forms.EmailField(max_length=100, help_text='Required, Enter Valid Email Address')

	class Meta:
		model = User
		fields =['username', 'first_name', 'last_name','email', 'password1', 'password2']


class DocForm(forms.ModelForm):

	class Meta:
		model = Documents
		fields = ['Birth_Certificate', 'Degree_Certificate']

DocumentVerification/docker/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import PageNotAnInteger, Paginator, PageNotAnInteger
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from .models import Documents
from .forms import SignUpForm, DocForm
# Create your views here.
def home(request):
	return render(request, 'index.html')

@user_passes_test(lambda u: u.is_superuser)
def UserListView(request):
	users  = User.objects.all().exclude(is_superuser=True)
	page = request.GET.get('page')
	paginator = Paginator(users, 6)
	try:
		teacherss = paginator.get_page(page)
	except PageNotAnInteger:
		teacherss = paginator.get_page(1)
	except EmptyPage:
		teacherss = paginator.get_page(paginator.numbers)
	context={'teacher':teacherss}
	return render(request, 'userlist.html', context)

@login_required
def DocumentListView(request):
	try:
		docs  = Documents.objects.get(user=request.user)
		context={'teacher':docs}
		return render(request, 'doclist.html', context)
	except Documents.DoesNotExist:
		return HttpResponse('Sorry You Are Yet Uploaded file')

@user_passes_test(lambda u: u.is_superuser)
def DocVerify(request, userid):
	try:
		user  = User.objects.get(id=userid)
		Documents.objects.filter(user=user).update(Verification=True)
		return redirect('docker:home')
	except User.DoesNotExist:
		return Http404

@user_passes_test(lambda u: u.is_superuser)
def PersonDocumentView(request, userid):
	try:
		docs  = User.objects.get(id=userid)
	except User.DoesNotExist:
		raise Http404
	context={'teacher':docs}
	return render(request, 'docviewlist.html', context)

@login_required
def DocCreateView(request):
	if request.method == "POST":
		form = DocForm(request.POST, request.FILES)
		if form.is_valid():
			newdoc = Documents(Birth_Certificate=request.FILES['Birth_Certificate'],Degree_Certificate=request.FILES['Degree_Certificate'])
			newdoc.user = request.user
			newdoc.save()
			return redirect('docker:doclist')
	else:
		form = DocForm()
	context = {'form':form}
	return render(request, 'docform.html', context)

@login_required
def DeleteDoc(request, docid):
	doc = Documents.objects.get(user_id=docid)
	doc.delete()
	return HttpResponseRedirect(reverse('docker:home'))

def SignUpView(request):
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('docker:home')
	else:
		form = SignUpForm()
	context = {'form':form}
	return render(request, 'signupform.html', context)


def LogotView(request):
	logout(request)
	return redirect('docker:home')

DocumentVerification/docker/templates/docform.html
{% extends 'index.html' %}
{% load static %}
{% load bootstrap4 %}
{% block additional_styles %}
	<link rel="stylesheet" type="text/css" href="{% static "style2.css" %}">
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
                <div class="col-12 text-left">
                    <a href="#menu-toggle" class="btn btn-success btn-lg" id="menu-toggle">Menu</a>
                </div>
                </div>
                <br>

	<div class="jumbotron">
	 <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active" 
        style="color:#fff;
        font-size:30px;
        font-family:bold;
       margin:auto;">
    Documents </li>
      </ol>
		<form method="POST" enctype="multipart/form-data" class="form">
			{% csrf_token %}
			{%  bootstrap_form form %}
			{% buttons %}
        		<div class="row">
                <div class="col-12 text-center">
                    <button type="submit" class="btn btn-success">Upload</button>
                </div>
                </div>
    		{% endbuttons %}
		</form>
	
	</div>
</div>
{% endblock %}

DocumentVerification/docker/templates/doclist.html
{% extends 'index.html' %}
{% load static %}
{% load bootstrap4 %}
{% block additional_styles %}
  <link rel="stylesheet" type="text/css" href="{% static "style2.css" %}">
{% endblock %}
{% block content%}
{% if teacher %}
<div class="container">
      <div class="row">
                <div class="col-12 text-left">
                    <a href="#menu-toggle" class="btn btn-success btn-lg" id="menu-toggle">Menu</a>
                </div>
      </div>
                <br>

            <div class="jumbotron">
             <ol class="breadcrumb my-4">
                  <li class="breadcrumb-item active" 
                  style="color:#fff;
                  font-size:30px;
                  font-family:bold;
                 margin:auto;">
              Document Lists </li>
                </ol>
        <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
          <th>Birth Certificate</th>
          <th>Degree Certificate</th>
          <th>Delete</th>
          <th>Verification</th>
        </tr>
      </thead>
      <tbody>

          <tr>
            <td class="align-middle"><a href="{{ teacher.Birth_Certificate.url }}"> {{ teacher.Birth_Certificate.name}}</a></td>
             <td class="align-middle"><a href="{{ teacher.Degree_Certificate.url }}"> {{ teacher.Degree_Certificate.name}}</a></td>
             <td class="align-middle"><a href="{% url "docker:docdelete" teacher.user.id %}"><ion-icon name="trash" class="iconitemdelete"></ion-icon></ion-icon></a></td>
             {% if teacher.Verification %}
             <td class="align-middle"><ion-icon name="checkmark" class="iconitemdelete" style="font-size:30px;color:green"></ion-icon></ion-icon></a></td>
             {% else %}
            <td class="align-middle"><ion-icon name="close" style="font-size:30px; color:red;"></ion-icon></ion-icon></a></td>
            {% endif %}

          </tr>

      </tbody>
    </table>
  </div>
  </div>
 

{% else %}
<h3 style="color:white">No documets</h3>
{% endif %}
{% endblock %}

DocumentVerification/docker/templates/docviewlist.html
{% extends 'index.html' %}
{% load static %}
{% load bootstrap4 %}
{% block additional_styles %}
  <link rel="stylesheet" type="text/css" href="{% static "style2.css" %}">
{% endblock %}
{% block content%}
{% if teacher.documents %}
<div class="container">
      <div class="row">
                <div class="col-12 text-left">
                    <a href="#menu-toggle" class="btn btn-success btn-lg" id="menu-toggle">Menu</a>
                </div>
      </div>
                <br>

            <div class="jumbotron">
             <ol class="breadcrumb my-4">
                  <li class="breadcrumb-item active" 
                  style="color:#fff;
                  font-size:30px;
                  font-family:bold;
                 margin:auto;">
              Document Lists </li>
                </ol>
        <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
          <th>Birth Certificate</th>
          <th>Degree Certificate</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td class="align-middle"><a href="{{ teacher.documents.Birth_Certificate.url }}"> {{ teacher.documents.Birth_Certificate.name}}</a></td>
             <td class="align-middle"><a href="{{ teacher.documents.Degree_Certificate.url }}" > {{ teacher.documents.Degree_Certificate.name}}</a></td>

          </tr>


      </tbody>
    </table>
    {% buttons %}
            <div class="row">
                <div class="col-12 text-center">
                    <a href="{% url "docker:docverify" teacher.id %}" class="btn btn-success  active" role="button" aria-pressed="true" >Confirm Verification</a>
                </div>
                </div>
    {% endbuttons %}
  </div>
  </div>
 

{% else %}
<h3 style="color:white">No documets</h3>
{% endif %}
{% endblock %}

DocumentVerification/docker/templates/index.html
{% load staticfiles %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Document Verification</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/simple-sidebar.css" %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "style1.css" %}">
    {% block additional_styles %}
    {% endblock %}

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav" style="font-family:bold;">
                <li class="sidebar-brand">
                    {% if request.user.is_authenticated %}
                    <a href="#">
                       Welcome {{ user.username }}
                    </a>
                    {% else %}
                    <a href="{% url "docker:login" %}">
                        Login Here
                    </a>
                    {% endif %}
                </li>
                <li>
                    <a href="{% url "docker:home" %}">Home</a>
                </li>
                {% if request.user.is_superuser%}
                <li>
                    <a href="{% url "docker:userlist" %}">Customers</a>
                </li>
                {%else%}
                {% if request.user.is_authenticated %}
                {% if request.user.documents %}
                <li>
                    <a href="{% url "docker:doclist" %}">Documents</a>
                </li>
                {% else %}
                 <li>
                    <a href="{% url "docker:newdoc" %}">Upload Documents</a>
                </li>
                {% endif %}
                {% endif %}
                {% endif %}
                {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url "docker:logout" %}">
                        Logout
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            {% block content %}
            <div class="container-fluid text-white">
                <br>
                <br>
                <h1 class="display-1 text-center">Document Verification System</h1>
                <br>
                <br>
                  <div class="row">
                <div class="col-12 text-center">
                    <a href="#menu-toggle" class="btn btn-success btn-lg" id="menu-toggle">Menu</a>
                </div>
                </div>
                
            </div>
            {% endblock %}
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Bootstrap core JavaScript -->
     <script src="https://unpkg.com/ionicons@4.5.0/dist/ionicons.js"></script>
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

DocumentVerification/docker/templates/login.html
{% extends 'index.html' %}
{% load static %}
{% load bootstrap4 %}
{% block additional_styles %}
	<link rel="stylesheet" type="text/css" href="{% static "style2.css" %}">
{% endblock %}
{% block nav%}
<a class="menu-toggle rounded" href="#">
  <i class="fas fa-bars"></i>
</a>
{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
                <div class="col-12 text-left">
                    <a href="#menu-toggle" class="btn btn-success btn-lg" id="menu-toggle">Menu</a>
                </div>
                </div>
                <br>

	<div class="jumbotron">
	 <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active" 
        style="color:#fff;
        font-size:30px;
        font-family:bold;
       margin:auto;">
    Login </li>
      </ol>
		<form method="POST" enctype="multipart/form-data" class="form">
			{% csrf_token %}
			{%  bootstrap_form form %}
			{% buttons %}
                    <button type="submit" class="btn btn-success" style="display:inline;">Login</button>


   
                    <a href="{% url "docker:signup" %}" class="btn btn-success  active" role="button" aria-pressed="true" style="display:inline; margin-left:800px;">Create New Account</a>
            
         
            
              
    		{% endbuttons %}
            
            <input type="hidden" name="next" value="{% url 'docker:home' %}">
		</form>
	
	</div>
</div>
{% endblock %}

DocumentVerification/docker/templates/signupform.html
{% extends 'index.html' %}
{% load static %}
{% load bootstrap4 %}
{% block additional_styles %}
	<link rel="stylesheet" type="text/css" href="{% static "style2.css" %}">
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
                <div class="col-12 text-left">
                    <a href="#menu-toggle" class="btn btn-success btn-lg" id="menu-toggle">Menu</a>
                </div>
                </div>
                <br>

	<div class="jumbotron">
	 <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active" 
        style="color:#fff;
        font-size:30px;
        font-family:bold;
       margin:auto;">
    SignUp </li>
      </ol>
		<form method="POST" enctype="multipart/form-data" class="form">
			{% csrf_token %}
			{%  bootstrap_form form %}
			{% buttons %}
        		<div class="row">
                <div class="col-12 text-center">
                    <button type="submit" class="btn btn-success">SignUp</button>
                </div>
                </div>
    		{% endbuttons %}
		</form>
	
	</div>
</div>
{% endblock %}

DocumentVerification/docker/templates/userlist.html
{% extends 'index.html' %}
{% load static %}
{% load bootstrap4 %}
{% block additional_styles %}
  <link rel="stylesheet" type="text/css" href="{% static "style2.css" %}">
{% endblock %}
{% block content%}
{% if teacher %}
<div class="container">
      <div class="row">
                <div class="col-12 text-left">
                    <a href="#menu-toggle" class="btn btn-success btn-lg" id="menu-toggle">Menu</a>
                </div>
      </div>
                <br>

            <div class="jumbotron">
             <ol class="breadcrumb my-4">
                  <li class="breadcrumb-item active" 
                  style="color:#fff;
                  font-size:30px;
                  font-family:bold;
                 margin:auto;">
              Customer Lists </li>
                </ol>
        <table class="table table-bordered">
        <thead class="thead-dark">
        <tr style="text-align:center;">
          <th>User Name</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Verification</th>
        </tr>
      </thead>
      <tbody>
        {% for teachers in teacher %}
          <tr style="text-align:center;">
            <td class="align-middle">
              {{ teachers.username }}
            </td>
            <td class="align-middle">{{ teachers.first_name}}</td>
            <td class="align-middle">{{ teachers.last_name}}</td>
            <td class="align-middle">{{ teachers.email}}</td>
            {% if teachers.documents.Verification%}
             <td class="align-middle"><ion-icon name="checkmark" class="iconitemdelete" style="font-size:30px;color:green"></ion-icon></ion-icon></a></td>
             {% else %}
            <td class="align-middle"><a href="{% url "docker:docview" teachers.id %}"><ion-icon name="eye" style="font-size:30px;"></ion-icon></ion-icon></a></td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>



<nav aria-label="Page navigation example">
<ul class="pagination">
        {% if teacher.has_previous %}
        
        <li class="page-item"><a class="page-link" href="?page={{ teacher.previous_page_number }}">&laquo;</a></li>
        {% endif %}
        {% for i in teacher.paginator.page_range %}
      {% if teacher.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    	{% endfor %}
     

        {% if teacher.has_next %}
           <li class="page-item"> <a class="page-link" href="?page={{ teacher.next_page_number }}">&raquo;</a></li>
            {% endif %}
</ul>
</nav>

  </div>
  </div>
 

{% else %}
<h3>No Students</h3>
{% endif %}
{% endblock %}